const diccionario = {
    A: ["Algoritmo", "Aplicacion", "Almacenamiento","Arquitectura de sofware", "Analisis de datos"],
    B: ["Big Data", "Byte ", "Bluetooth","Bases de datos","Bit"],
    C: ["CPU ", "Compilador ", "Cable de red","Código fuente","Cloud Computing"],
    D: ["Datos","Disco duro","Depuración","DNS","Driver"],
    E: [" ", "Encriptación", "E-learning", "ERP","E-mEthernetail "],
    F: ["Firewall", "Firmware", "FTP","Framework ","Formulario"],
    G: ["Git","Gigabyte (GB","GPU ","Gateway","Google Drive"],
    H: ["Hardware ","HTML ","Hosting ","HTTP","Hacker",],
    I: ["IP","IA","Intranet","Informática","Instalador"],
    J: ["Java ","JavaScript","JSON ","JQuery","Jenkins,"],
    K: ["Kernel","Kbps","Kali Linux","Keylogger","Kubernetes"],
    L: ["Linux","Lenguaje de programación ", "Login", "Licencia de software", "LAN "],
    M: ["Malware", "Memoria RAM","Metadatos","Monitor ", "Mainframe"],
    N: ["Nube (Cloud)","Nombre de dominio", "Navegador (Browser) ","NIC (Network Interface Card)","Nodo "],
    O: ["Open Source (Código Abierto) ","Office (Microsoft Office) ","OCR (Reconocimiento Óptico de Caracteres) ","Operating System (Sistema Operativo)","Overclocking"],
    P: ["Procesador ","PHP ","Pantalla táctil ","Ping","Python"],
    Q: ["Query (Consulta)","QoS (Quality of Service)", "QuickTime", "Quarantine (Cuarentena)","Quantum computing (Computación cuántica) "],
    R: ["Red", "RAM", "Router ","Router ","RAID "],
    S: ["Servidor", "Sistema Operativo ","Software","Script ","Seguridad informática"],
    T: ["Tarjeta madre (Motherboard)","Teclado ","Token", "Thunderbolt","TCP/IP "],
    U: ["URL ","Usuario ","USB","Update","Ubuntu "],
    V: ["Virtualización","Virus ","VPN (Virtual Private Network)","VoIP ","Visual Studio"],
    W: ["Web","Wi-Fi ", "Windows","Webcam","WordPress "],
    X: ["XML","XSS (Cross-Site Scripting)","XAMPP","X.509","Xbox Live "],
    Y: ["Yottabyte","YouTube","YAML","Yahoo","Yield"],
    Z: ["ZIP","Zona DNS","Zettabyte","Zero-day ","Zoom"]
   
  };
  